### ISSUE TITLE
Published version doesn't match docs

### ISSUE THREAD

**Issue by joaomilho** [pmros/graflow#1]
So the published npm version doesn't create "on" method, for instance. Dist code is still like this:

```js
	var toComponent = function toComponent(arg) {
	  if ((typeof arg === 'undefined' ? 'undefined' : _typeof(arg)) === 'object') return arg;
	  var node = toNode(arg);
	  return {
	    start: function start() {
	      var v = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
	      return node.received(v);
	    },
	    inputs: { default: node },
	    outputs: { default: node },
	    in: { default: node },
	    out: { default: node }
	  };
	};
```

**Comment by pmros** [comment]
I'm sorry! You are right. I forgot build graflow 0.3.0 before upload to Github! Sorry again!
I've just released graflow 0.3.1. Live example:
https://www.webpackbin.com/bins/-KecjX2KqEQzZtXATCMj

Thank you @joaomilho.

**Comment by joaomilho** [comment]
Apparently WebpackBin's console.log only logs the first arg. If I run the same with node I get:

```
$ node test.js
3 [Function: next]
4 [Function: next]
5 [Function: next]
```

**Comment by pmros** [comment]
You are right again. Fixed! Thank you!
